### ISSUE TITLE
Error starting simple-chat-api on Windows

### ISSUE THREAD

**Issue by johnotu** [teamintrepid/simple-chat-api#2]
For some weird reason `npm start` didn't work for me. It raised a *'NODE_ENV' is not recognized as an internal or external command, operable program or batch file.* error.
I fixed it by adding `set` and `&&` to the *start script* in **package.json**  like so 
`set NODE_ENV=development && node ./lib/app.js`
Note that I needed `&&` because after adding `set` it was just setting the environment without starting the server.

Maybe you could include this in the **README.md** to help Windows users.

**Comment by paul-pagnan** [comment]
Hi John,

Thanks for alerting the issue. Could you perhaps try just removing the the NODE_ENV from the start script altogether, we never actually reference it in the code, so it's place here is redundant.

The start script would simply become "node ./lib/app,js".

Please let me know if that works on your windows environment, if so would you please be so kind as to resubmit your PR with these changes.

**Comment by johnotu** [comment]
Yeah, that was a more elegant solution. I was thinking there might be environment variables that can change between development and production but that can be managed by whoever uses the API.
I pushed the latest commit and have confirmed the PR is updated. Or would you like me to send a different one entirely?

**Comment by paul-pagnan** [comment]
That's fine, I have merged the PR, thanks!
